import type { BrazilAccount } from './types'

// Approximate HQ coordinates for Brazilian cities used below.
const SAO_PAULO = { lat: -23.5505, lon: -46.6333, city: 'São Paulo' }
const RIO_DE_JANEIRO = { lat: -22.9068, lon: -43.1729, city: 'Rio de Janeiro' }
const BRASILIA = { lat: -15.7939, lon: -47.8828, city: 'Brasília' }

export const BRAZIL_ACCOUNTS: BrazilAccount[] = [
  {
    id: 'apex-group-brazil',
    name: 'Apex Group Brazil',
    clientTypes: ['ThirdPartyAdministrator'],
    primaryShape: 'triangle',
    status: 'Disabled',
    temperatureScore: 15,
    ...SAO_PAULO,
    openOpportunityCount: 0,
    openOpportunityValue: 0,
    owner: 'Camila Rocha',
  },
  {
    id: 'vortx',
    name: 'Vortx',
    clientTypes: ['ThirdPartyAdministrator'],
    primaryShape: 'triangle',
    status: 'Prospect',
    temperatureScore: 25,
    ...SAO_PAULO,
    openOpportunityCount: 1,
    openOpportunityValue: 180_000,
    latestSignal: {
      headline: 'Initial outreach call scheduled with Vortx operations team',
      date: '2026-06-12',
      source: 'Salesforce',
    },
    owner: 'Lucas Ferreira',
  },
  {
    id: 'banco-santander-brazil',
    name: 'Banco Santander Brazil',
    clientTypes: ['Distributor'],
    primaryShape: 'circle',
    status: 'InDiscussions',
    temperatureScore: 35,
    ...SAO_PAULO,
    openOpportunityCount: 2,
    openOpportunityValue: 620_000,
    latestSignal: {
      headline: 'Santander evaluating cross-border order routing for LatAm retail range',
      date: '2026-06-18',
      source: 'Notion',
    },
    owner: 'Camila Rocha',
  },
  {
    id: 'xp',
    name: 'XP',
    clientTypes: ['Distributor'],
    primaryShape: 'circle',
    status: 'InDiscussions',
    temperatureScore: 45,
    ...SAO_PAULO,
    openOpportunityCount: 3,
    openOpportunityValue: 940_000,
    latestSignal: {
      headline: 'XP platform team requested a technical workshop on ISO 20022 messaging',
      date: '2026-06-22',
      source: 'Salesforce',
    },
    owner: 'Lucas Ferreira',
  },
  {
    id: 'bny-mellon-servicos-dtvm',
    name: 'BNY Mellon Servicos DTVM',
    clientTypes: ['ThirdPartyAdministrator'],
    primaryShape: 'triangle',
    status: 'Live',
    temperatureScore: 52,
    ...BRASILIA,
    openOpportunityCount: 2,
    openOpportunityValue: 410_000,
    latestSignal: {
      headline: 'BNY Mellon Servicos DTVM live on two settlement corridors, expansion under review',
      date: '2026-06-05',
      source: 'Salesforce',
    },
    owner: 'Camila Rocha',
  },
  {
    id: 'ubs-brazil',
    name: 'UBS',
    clientTypes: ['FundManager', 'Distributor'],
    primaryShape: 'hexagon',
    status: 'Live',
    temperatureScore: 58,
    ...RIO_DE_JANEIRO,
    openOpportunityCount: 2,
    openOpportunityValue: 780_000,
    latestSignal: {
      headline: 'UBS Brazil wealth desk expanding offshore fund shelf for HNW clients',
      date: '2026-06-14',
      source: 'News',
    },
    owner: 'Mariana Souza',
  },
  {
    id: 'bradesco',
    name: 'Bradesco',
    clientTypes: ['FundManager', 'Distributor'],
    primaryShape: 'hexagon',
    status: 'Live',
    temperatureScore: 68,
    ...SAO_PAULO,
    openOpportunityCount: 4,
    openOpportunityValue: 1_350_000,
    latestSignal: {
      headline: 'Bradesco Asset Management scaling instruction volumes ahead of Q3 launch',
      date: '2026-06-20',
      source: 'Salesforce',
    },
    owner: 'Mariana Souza',
  },
  {
    id: 'nubank',
    name: 'Nubank',
    clientTypes: ['Distributor'],
    primaryShape: 'circle',
    status: 'Live',
    temperatureScore: 78,
    ...SAO_PAULO,
    openOpportunityCount: 3,
    openOpportunityValue: 1_020_000,
    latestSignal: {
      headline: 'Nubank investment platform onboarding new fund shelf for digital-first investors',
      date: '2026-06-25',
      source: 'News',
    },
    owner: 'Lucas Ferreira',
  },
  {
    id: 'btg-pactual-brazil',
    name: 'BTG Pactual Brazil',
    clientTypes: ['FundManager', 'Distributor'],
    primaryShape: 'hexagon',
    status: 'Live',
    temperatureScore: 88,
    ...SAO_PAULO,
    openOpportunityCount: 5,
    openOpportunityValue: 2_150_000,
    latestSignal: {
      headline: 'BTG Pactual expanding cross-border distribution into Mexico and Chile corridors',
      date: '2026-06-27',
      source: 'Salesforce',
    },
    owner: 'Mariana Souza',
  },
  {
    id: 'itau-unibanco',
    name: 'Itaú Unibanco',
    clientTypes: ['FundManager', 'Distributor'],
    primaryShape: 'hexagon',
    status: 'Live',
    temperatureScore: 92,
    ...SAO_PAULO,
    openOpportunityCount: 4,
    openOpportunityValue: 2_600_000,
    latestSignal: {
      headline: 'Itaú UCITS launch needs Brazil–Luxembourg settlement bridge',
      date: '2026-05-15',
      source: 'Regulator',
    },
    owner: 'Camila Rocha',
  },
]
